import xml.etree.ElementTree as ET
import json
import os
import re

def extract_svg_paths(svg_file, output_ts):
    tree = ET.parse(svg_file)
    root = tree.getroot()
    
    # Remove XML namespaces to simplify path selection
    for el in root.iter():
        if '}' in el.tag:
            el.tag = el.tag.split('}', 1)[1]
            
    paths = []
    # Find all path elements
    for path in root.findall('.//path'):
        d = path.get('d')
        if d:
            # Clean up the path data (remove extra spaces/newlines)
            d = ' '.join(d.split())
            paths.append(d)
            
    print(f"Found {len(paths)} paths.")
    
    # Generate TypeScript file
    with open(output_ts, 'w') as f:
        f.write("/**\n")
        f.write(" * MAP_PATHS - Extracted country paths from map.svg\n")
        f.write(" * Automatically generated by extract-map-paths.py\n")
        f.write(" */\n\n")
        f.write("export interface MapPath {\n")
        f.write("  id: string;\n")
        f.write("  d: string;\n")
        f.write("}\n\n")
        f.write("export const MAP_PATHS: MapPath[] = [\n")
        
        for i, d in enumerate(paths):
            f.write(f'  {{ id: "c{i+1}", d: "{d}" }},\n')
            
        f.write("];\n")

if __name__ == "__main__":
    pwd = os.getcwd()
    svg_path = os.path.join(pwd, "public", "map.svg")
    output_path = os.path.join(pwd, "components", "svg", "map-paths.ts")
    
    if not os.path.exists(svg_path):
        print(f"Error: {svg_path} not found.")
    else:
        extract_svg_paths(svg_path, output_path)
        print(f"Successfully generated {output_path}")
